/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/ui/checkbox/Checkbox.vue')['default']
    Command: typeof import('./src/components/ui/command/Command.vue')['default']
    CommandEmpty: typeof import('./src/components/ui/command/CommandEmpty.vue')['default']
    CommandGroup: typeof import('./src/components/ui/command/CommandGroup.vue')['default']
    CommandInput: typeof import('./src/components/ui/command/CommandInput.vue')['default']
    CommandItem: typeof import('./src/components/ui/command/CommandItem.vue')['default']
    CommandList: typeof import('./src/components/ui/command/CommandList.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    GreetComponent: typeof import('./src/components/GreetComponent.vue')['default']
    ImportExportDialog: typeof import('./src/components/settings/ImportExportDialog.vue')['default']
    ImportExportSettings: typeof import('./src/components/settings/ImportExportSettings.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    LauncherDialog: typeof import('./src/components/settings/LauncherDialog.vue')['default']
    LauncherManager: typeof import('./src/components/settings/LauncherManager.vue')['default']
    Pagination: typeof import('./src/components/ui/pagination/Pagination.vue')['default']
    ProjectContextMenu: typeof import('./src/components/ProjectContextMenu.vue')['default']
    ProjectDialog: typeof import('./src/components/settings/ProjectDialog.vue')['default']
    ProjectListItem: typeof import('./src/components/ProjectListItem.vue')['default']
    ProjectManager: typeof import('./src/components/settings/ProjectManager.vue')['default']
    ProjectTypeIcon: typeof import('./src/components/ProjectTypeIcon.vue')['default']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    Switch: typeof import('./src/components/ui/switch/Switch.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/tabs/TabsTrigger.vue')['default']
    Tooltip: typeof import('./src/components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./src/components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./src/components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./src/components/ui/tooltip/TooltipTrigger.vue')['default']
    VcsIcon: typeof import('./src/components/VcsIcon.vue')['default']
  }
}
